### ISSUE TITLE
#Issue02: Can't get data transfer listView to editText

### ISSUE THREAD

**Issue by huynhminhsangit** [huynhminhsangit/Simple-Todo-List#2]
![guide](https://cloud.githubusercontent.com/assets/16367000/26596608/8ab410de-4599-11e7-96ec-6dddecb249c9.gif)

**Comment by huynhminhsangit** [comment]
Done

**Comment by nongdenchet** [comment]
### Thank you for your submission
- You really pushed effort on doing the prework, I really appreciate that

### Good stuffs
- Nice to see action bar
- Nice to see the action bar custom icon
- You have used adapter and listview
- File implement is great
- The dialog is really nice

### Suggestions
- Currently we are receiving a lot of good submissions
- I would love to let you in the class but I would love to see you polish the UI and do more optional stuffs
- Can you try implement SQLite database and adding the calendar to pickup the the due date of the todo

**Comment by huynhminhsangit** [comment]
@nongdenchet  Thank you for the suggestion. I will update it for the best.

**Comment by nongdenchet** [comment]
Thank you, hope to see your new update soon
